# Generated by Django 5.0.6 on 2024-06-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='enorllment_term_id',
            new_name='enrollment_term_id',
        ),
    ]
