# Generated by Django 5.0.6 on 2024-07-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_user_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='user',
        ),
    ]
