# Generated by Django 5.0.6 on 2024-07-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_users_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
