# Generated by Django 5.0.6 on 2024-07-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_course_name_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='distribution',
            field=models.JSONField(null=True),
        ),
    ]
