# Generated by Django 5.0.6 on 2024-08-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='distribution',
        ),
    ]
