# Generated by Django 5.0.6 on 2024-08-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='was_user_created',
            field=models.BooleanField(default=False),
        ),
    ]
