# Generated by Django 5.0.6 on 2024-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_courses', '0001_initial'),
        ('users', '0002_user_courses_user_session_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='user_courses.usercourse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_avg',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
