# Generated by Django 5.0.6 on 2024-08-28 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_content',
        ),
        migrations.AddField(
            model_name='resource',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
