# Generated by Django 5.0.6 on 2024-06-25 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_type', models.CharField(choices=[('TUT', 'Tutorial'), ('PRA', 'Lab'), ('LAB', 'Lab')], max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollment_term_id', models.IntegerField()),
                ('lecture_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
