# Generated by Django 4.1.13 on 2024-04-27 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('user_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('submission_link', models.CharField(max_length=255)),
                ('submission_status', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_courses.usercourse')),
                ('resources', models.ManyToManyField(related_name='resources', to='resources.resource')),
            ],
        ),
    ]
