# Generated by Django 5.0.6 on 2024-08-12 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_course_distribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('homework_assignments', models.IntegerField(default=0)),
                ('quizzes', models.IntegerField(default=0)),
                ('tests', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('exams', models.IntegerField(default=0)),
                ('labs', models.IntegerField(default=0)),
                ('other_weight', models.IntegerField(default=0)),
                ('other_description', models.CharField(max_length=255, null=True)),
                ('total_points', models.IntegerField(default=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
