# Generated by Django 5.0.6 on 2024-08-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='course',
        ),
        migrations.AddField(
            model_name='distribution',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
    ]
