# Generated by Django 5.0.6 on 2024-07-15 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_distribution'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='task',
            name='submission_status',
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
