# Generated by Django 5.0.6 on 2024-08-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_course_task_course_id_task_html_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='points_possible',
            field=models.FloatField(default=100),
        ),
    ]
