# Generated by Django 5.0.6 on 2024-08-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_grade_task_notes_alter_task_points_possible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='TO-DO', max_length=255),
        ),
    ]
